# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


def sum_of_even_number_fibonacci_1(max):
    prev = 0
    curr = 1
    nextTerm = 0
    total = 0

    while curr <= max:
        nextTerm = prev + curr
        prev = curr
        curr = nextTerm
        if(curr % 2 == 0):
            total += curr
        print(curr, end=", ")

    return total


def sum_of_even_number_fibonacci_2(max):
    prev, curr = 1, 2
    total = 0

    while curr <= max:
        # Swapping happens in a single line.
        prev, curr = curr, (prev + curr)
        if(curr % 2 == 0):
            total += curr
        print(curr, end=", ")

    return total


total = sum_of_even_number_fibonacci_1(4000000)
print()
print(total)

total = sum_of_even_number_fibonacci_2(4000000)
print()
print(total)
